server:
  port: 8888

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  type-aliases-package: com.study.modle
  mapper-locations: classpath:/mapper/*
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    path: logs
